services:
  - type: web
    name: adanma-engineering
    runtime: static
    buildCommand: npm run build
    staticPublishPath: dist
    startCommand: npm start
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: "/*.html"
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
